package iesdomingoperezminik.es.proyectofinal.model;

public enum Error {

    EMPTY_NAME, EMPTY_SURNAME, ALREADY_REGISTERED, EMPTY_EMAIL, EMPTY_PASSWORD, INVALID_EMAIL, PASSWORD_MISMATCH, PASSWORD_LENGTH,
    EMAIL_NOT_FOUND, INVALID_PASSWORD

}
